#!/usr/bin/sh

sxhkd >& /tmp/sxhkd.log &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a alacritty desktop=^1 follow=off focus=on
bspc rule -a firefox desktop=^2 follow=off
bspc rule -a slack desktop=^8 follow=off
bspc rule -a caprine desktop=^9 follow=off

$HOME/.config/polybar/launch.sh
