name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

env:
  IMAGE: dotfiles

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the tag
      id: tag
      run: echo "::set-output name=tag::$(git rev-parse --short HEAD).$(date +'%Y-%m-%d')"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: "{{defaultContext}}:.docker/debian"
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:v${{ github.run_number }}.${{ steps.tag.outputs.tag }}
        # cache-from: |
        #   marcpartensky/dotfiles:cache
        #   type=local,src=path/to/dir
