name: Docker

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]

env:
  IMAGE: dotfiles

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        path: .docker/debian
        push: true
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:$(echo $(date +%Y%m%d-%H%M%S).$(git log -1 --pretty=%h))
        # tags: ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE:latest
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/dotfiles:latest
